/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TaskersRouteImport } from './routes/taskers'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TaskerUserIdRouteImport } from './routes/tasker.$userId'
import { Route as JobJobIdRouteImport } from './routes/job.$jobId'
import { Route as AuthenticatedTaskerRouteImport } from './routes/_authenticated/tasker'
import { Route as AuthenticatedPostJobRouteImport } from './routes/_authenticated/post-job'
import { Route as AuthenticatedEditProfileRouteImport } from './routes/_authenticated/edit-profile'
import { Route as AuthenticatedClientRouteImport } from './routes/_authenticated/client'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedBookingBookingIdRouteImport } from './routes/_authenticated/booking.$bookingId'

const TaskersRoute = TaskersRouteImport.update({
  id: '/taskers',
  path: '/taskers',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskerUserIdRoute = TaskerUserIdRouteImport.update({
  id: '/tasker/$userId',
  path: '/tasker/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobJobIdRoute = JobJobIdRouteImport.update({
  id: '/job/$jobId',
  path: '/job/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTaskerRoute = AuthenticatedTaskerRouteImport.update({
  id: '/tasker',
  path: '/tasker',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostJobRoute = AuthenticatedPostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEditProfileRoute =
  AuthenticatedEditProfileRouteImport.update({
    id: '/edit-profile',
    path: '/edit-profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientRoute = AuthenticatedClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingBookingIdRoute =
  AuthenticatedBookingBookingIdRouteImport.update({
    id: '/booking/$bookingId',
    path: '/booking/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/taskers': typeof TaskersRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/client': typeof AuthenticatedClientRoute
  '/edit-profile': typeof AuthenticatedEditProfileRoute
  '/post-job': typeof AuthenticatedPostJobRoute
  '/tasker': typeof AuthenticatedTaskerRoute
  '/job/$jobId': typeof JobJobIdRoute
  '/tasker/$userId': typeof TaskerUserIdRoute
  '/booking/$bookingId': typeof AuthenticatedBookingBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/taskers': typeof TaskersRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/client': typeof AuthenticatedClientRoute
  '/edit-profile': typeof AuthenticatedEditProfileRoute
  '/post-job': typeof AuthenticatedPostJobRoute
  '/tasker': typeof AuthenticatedTaskerRoute
  '/job/$jobId': typeof JobJobIdRoute
  '/tasker/$userId': typeof TaskerUserIdRoute
  '/booking/$bookingId': typeof AuthenticatedBookingBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/taskers': typeof TaskersRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/client': typeof AuthenticatedClientRoute
  '/_authenticated/edit-profile': typeof AuthenticatedEditProfileRoute
  '/_authenticated/post-job': typeof AuthenticatedPostJobRoute
  '/_authenticated/tasker': typeof AuthenticatedTaskerRoute
  '/job/$jobId': typeof JobJobIdRoute
  '/tasker/$userId': typeof TaskerUserIdRoute
  '/_authenticated/booking/$bookingId': typeof AuthenticatedBookingBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/taskers'
    | '/bookings'
    | '/client'
    | '/edit-profile'
    | '/post-job'
    | '/tasker'
    | '/job/$jobId'
    | '/tasker/$userId'
    | '/booking/$bookingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/taskers'
    | '/bookings'
    | '/client'
    | '/edit-profile'
    | '/post-job'
    | '/tasker'
    | '/job/$jobId'
    | '/tasker/$userId'
    | '/booking/$bookingId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/taskers'
    | '/_authenticated/bookings'
    | '/_authenticated/client'
    | '/_authenticated/edit-profile'
    | '/_authenticated/post-job'
    | '/_authenticated/tasker'
    | '/job/$jobId'
    | '/tasker/$userId'
    | '/_authenticated/booking/$bookingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TaskersRoute: typeof TaskersRoute
  JobJobIdRoute: typeof JobJobIdRoute
  TaskerUserIdRoute: typeof TaskerUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/taskers': {
      id: '/taskers'
      path: '/taskers'
      fullPath: '/taskers'
      preLoaderRoute: typeof TaskersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasker/$userId': {
      id: '/tasker/$userId'
      path: '/tasker/$userId'
      fullPath: '/tasker/$userId'
      preLoaderRoute: typeof TaskerUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job/$jobId': {
      id: '/job/$jobId'
      path: '/job/$jobId'
      fullPath: '/job/$jobId'
      preLoaderRoute: typeof JobJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasker': {
      id: '/_authenticated/tasker'
      path: '/tasker'
      fullPath: '/tasker'
      preLoaderRoute: typeof AuthenticatedTaskerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/post-job': {
      id: '/_authenticated/post-job'
      path: '/post-job'
      fullPath: '/post-job'
      preLoaderRoute: typeof AuthenticatedPostJobRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/edit-profile': {
      id: '/_authenticated/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof AuthenticatedEditProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client': {
      id: '/_authenticated/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof AuthenticatedClientRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/booking/$bookingId': {
      id: '/_authenticated/booking/$bookingId'
      path: '/booking/$bookingId'
      fullPath: '/booking/$bookingId'
      preLoaderRoute: typeof AuthenticatedBookingBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedClientRoute: typeof AuthenticatedClientRoute
  AuthenticatedEditProfileRoute: typeof AuthenticatedEditProfileRoute
  AuthenticatedPostJobRoute: typeof AuthenticatedPostJobRoute
  AuthenticatedTaskerRoute: typeof AuthenticatedTaskerRoute
  AuthenticatedBookingBookingIdRoute: typeof AuthenticatedBookingBookingIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedClientRoute: AuthenticatedClientRoute,
  AuthenticatedEditProfileRoute: AuthenticatedEditProfileRoute,
  AuthenticatedPostJobRoute: AuthenticatedPostJobRoute,
  AuthenticatedTaskerRoute: AuthenticatedTaskerRoute,
  AuthenticatedBookingBookingIdRoute: AuthenticatedBookingBookingIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TaskersRoute: TaskersRoute,
  JobJobIdRoute: JobJobIdRoute,
  TaskerUserIdRoute: TaskerUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
